arch:
  - aarch64
  - amd64
description: Unsupported - Xiaomi router firmware modification scripts (no longer maintained)
init: false
map:
  - share:rw
name: xqrepack
options:
  firmware_name: miwifi_r3600_firmware.bin
  firmware_path: /share/miwifi_firmware/
schema:
  firmware_name: str
  firmware_path: str
slug: xqrepack
image: ghcr.io/faserf/hassio-addons-xqrepack-{arch}
url: https://github.com/FaserF/hassio-addons/tree/master/xqrepack
version: 2.0.0
