arch:
  - aarch64
  - amd64
description: These scripts allow you to modify the different Xiaomi router firmware
  images to make sure SSH and UART access is always enabled. (Unsupported)
init: false
map:
  - share:rw
name: xqrepack (Unsupported)
options:
  firmware_name: miwifi_r3600_firmware.bin
  firmware_path: /share/miwifi_firmware/
schema:
  firmware_name: str
  firmware_path: str
slug: xqrepack
url: https://github.com/FaserF/hassio-addons/tree/master/xqrepack
version: 2.0.0
