---
name: Bash Script Executer (Edge)
version: 2.3.1-dev-c70fff0
slug: bashscriptexecuter
description: >-
  Execute your own bash scripts inside this Homeassistant App environment.
url: https://github.com/FaserF/hassio-addons/tree/master/bash_script_executer
arch:
  - aarch64
  - amd64
map:
  - share:rw
init: false
panel_icon: mdi:web-box
options:
  script_path: "/share/scripts/mycoolscript.sh"
  script_path2: "false"
  script_path3: "false"
  log_level: info
schema:
  script_path: str
  script_argument1: str?
  script_argument2: str?
  script_argument3: str?
  script_path2: str
  script2_argument1: str?
  script2_argument2: str?
  script2_argument3: str?
  script_path3: str
  script3_argument1: str?
  script3_argument2: str?
  script3_argument3: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)
