---
name: Planka
version: 0.1.2
slug: planka
image: ghcr.io/faserf/hassio-addons-planka-{arch}
description: The elegant open source project tracking tool
url: https://github.com/plankanban/planka
arch:
  - aarch64
  - amd64
map:
  - ssl
init: false
ingress: true
ingress_port: 1337
panel_icon: mdi:kanban
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  log_level: info
  secret_key: ""
  base_url: ""
schema:
  ssl: bool
  certfile: str
  keyfile: str
  log_level: list(error|warn|info|debug)
  secret_key: str?
  base_url: str?
ports:
  1337/tcp: 1337
ports_description:
  1337/tcp: Web Interface
