---
name: Planka (Edge)
version: 1.2.1-dev-c70fff0
slug: planka
description: The elegant open source project tracking tool
url: https://github.com/plankanban/planka
arch:
  - aarch64
  - amd64
map:
  - ssl
init: false
ingress: true
ingress_port: 1337
panel_icon: mdi:kanban
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  log_level: info
  secret_key: ""
  base_url: ""
schema:
  ssl: bool
  certfile: str
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  secret_key: str?
  base_url: str?
  reset_database: bool?
  reset_database_confirm: bool?
ports:
  1337/tcp: 11337
ports_description:
  1337/tcp: Web Interface
