---
name: AegisBot
version: "0.3.3"
slug: aegisbot
image: ghcr.io/faserf/hassio-addons-aegisbot-{arch}
description: Production-ready Telegram Moderation Bot with AI-driven FAQ and Security Features
url: https://github.com/FaserF/AegisBot
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_stream: true
panel_icon: mdi:robot
ports:
  8077/tcp: 8077
ports_description:
  8077/tcp: Web Interface (HTTP)
map:
  - type: share
    read_only: false
options:
  version: "latest"
  github_token: ""
  github_repo: "FaserF/AegisBot"
  developer_mode: false
  reset_database: false
  log_level: info
  database:
    type: sqlite
  secret_key: ""
  project_name: "AegisBot"
  debug: false
  demo_mode: false
  demo_mode_type: ephemeral
schema:
  version: str
  github_token: password?
  github_repo: str?
  developer_mode: bool
  reset_database: bool
  reset_database_confirm: bool?
  log_level: list(trace|debug|info|warning|error|fatal)?
  database:
    type: list(sqlite|postgresql)
    postgresql_host: str?
    postgresql_port: port?
    postgresql_user: str?
    postgresql_password: password?
    postgresql_database: str?
  secret_key: password?
  project_name: str?
  debug: bool?
  demo_mode: bool
  demo_mode_type: list(ephemeral|persistent)?
