---
name: Antigravity-Server (Edge)
version: "1.2.2-dev-c70fff0"
slug: antigravity-server
description: Stream the Antigravity AI IDE (Linux Desktop with XFCE4) via NoVNC in your browser.
url: https://github.com/FaserF/hassio-addons/tree/master/antigravity-server
arch:
  - amd64
init: false
ingress: true
ingress_port: 6080
panel_icon: mdi:rocket-launch
panel_title: Antigravity
map:
  - share:rw
ports:
  6080/tcp: 16080
  5901/tcp: 15901
ports_description:
  6080/tcp: "NoVNC Web Interface (use Ingress for secure access)"
  5901/tcp: "VNC Client Port"
options:
  vnc_password: ""
  log_level: info
  autostart_antigravity: true

schema:
  vnc_password: match(^.{0,8}$)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  autostart_antigravity: bool
