---
name: Komodo (Edge)
version: 0.1.1-dev-c70fff0
slug: komodo
description: A tool to build and deploy software on many servers
url: https://github.com/moghtech/komodo
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 9120
panel_icon: mdi:lizard
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
ports:
  9120/tcp: 19120
ports_description:
  9120/tcp: Web Interface
