arch:
- aarch64
- amd64
description: Unsupported - Bluetooth MQTT Gateway Server (no longer maintained) (Unsupported)
host_dbus: true
host_network: true
init: false
map:
- share
name: bt-mqtt-gateway
options:
  config_path: /share/bt-mqtt-gateway.yaml
  debug: false
panel_icon: mdi:bluetooth-transfer
schema:
  config_path: str
  debug: bool
services:
- mqtt:want
slug: bt-mqtt-gateway
image: ghcr.io/faserf/hassio-addons-bt-mqtt-gateway-{arch}
url: https://github.com/FaserF/hassio-addons/tree/master/bt-mqtt-gateway
version: 3.0.0
