name: xqrepack
version: 1.7.6
slug: xqrepack
description:
  These scripts allow you to modify the different Xiaomi router firmware
  images to make sure SSH and UART access is always enabled.
url: https://github.com/FaserF/hassio-addons/tree/master/xqrepack
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - share:rw
init: false
options:
  firmware_path: "/share/miwifi_firmware/"
  firmware_name: miwifi_r3600_firmware.bin
schema:
  firmware_path: str
  firmware_name: str
