---
name: pterodactyl Wings Gameserver
version: 2.0.0
slug: pterodactyl_wings
description: Open Source Gameserver
url: https://github.com/FaserF/hassio-addons/tree/master/pterodactyl-wings
arch:
  - aarch64
  - amd64
image: ghcr.io/faserf/hassio-addons-pterodactyl_wings-{arch}
# webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"
map:
  - share:rw
ingress: true
init: false
panel_icon: mdi:controller
options:
  config_file: /share/pterodactyl/config.yml
schema:
  config_file: str
ports:
  "2022": 2022
  8080/tcp: 8080
ports_description:
  8080/tcp: "8080"
  2022/tcp: "2022"
