---
name: N8n (Edge)
version: "1.2.1-dev-c70fff0"
slug: n8n
description: "Workflow automation tool. N8n extends your Home Assistant with powerful workflow automation."
url: "https://github.com/faserf/hassio-addons/tree/master/n8n"
arch:
  - aarch64
  - amd64
ingress: true
ingress_port: 5678
init: false
panel_icon: mdi:sitemap
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  log_level: info
  port: 5678
  listen_address: "0.0.0.0"
schema:
  ssl: bool?
  certfile: str?
  keyfile: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  port: int?
  listen_address: str?
ports:
  5678/tcp: 15678
ports_description:
  5678/tcp: Web Interface
