---
name: Switch LAN Play Client (Edge)
version: 2.3.1-dev-c70fff0
slug: switch-lan-play
description: Nintendo Switch Lan Play -Client
url: https://github.com/FaserF/hassio-addons/tree/master/switch_lan_play
arch:
  - amd64
init: false
panel_icon: mdi:local-area-network
host_network: true
host_ipc: true
host_dbus: true
options:
  server: "switch.lan-play.com:11451"
  log_level: info
schema:
  server: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)
ports: {}
