name: "Solumati"
version: "1.1.0"
slug: "solumati"
description: "The Anti-Swipe Revolution - Self-hosted dating platform focused on meaningful matches."
url: "https://github.com/FaserF/hassio-addons/tree/master/solumati"
startup: application
arch:
  - aarch64
  - amd64
init: false
map:
  - config:rw
  - share:rw
ports:
  80/tcp: 8099
ports_description:
  80/tcp: "Web Interface Port"
options:
  log_level: info
  test_mode: false
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  test_mode: bool
