name: "Solumati"
version: "0.1.1"
slug: "solumati"
description: "The Anti-Swipe Revolution. Open Source dating platform focused on meaningful matches."
url: "https://github.com/FaserF/hassio-addons/tree/master/solumati"
startup: application
arch:
  - aarch64
  - amd64
  - armv7
init: false
map:
  - config:rw
options:

  database_url: "postgresql://user:password@hostname-of-postgres-addon:5432/solumatidb"
  secret_key: "ChangeMeToSomethingSecure"
  log_level: "info"
schema:
  database_url: str
  secret_key: str
  log_level: list(debug|info|warning|error)
ingress: true
ingress_port: 8099
ports:
  8099/tcp: 8099
  7777/tcp: 7777