---
name: "Solumati"
version: "2.1.0"
slug: "solumati"
description: "The Anti-Swipe Revolution - Self-hosted dating platform focused on meaningful matches."
url: "https://github.com/FaserF/hassio-addons/tree/master/solumati"
arch:
  - aarch64
  - amd64
image: ghcr.io/faserf/hassio-addons-solumati-{arch}
init: false
ingress: true
panel_icon: mdi:heart-multiple
panel_title: Solumati
map:
  - homeassistant_config:rw
  - share:rw
ports:
  80/tcp: 8099
ports_description:
  80/tcp: "Web Interface Port (use Ingress for secure access)"
options:
  log_level: info
  test_mode: false
  app_base_url: ""
  factory_reset: false
  marketing_page_enabled: false
  dev_use_main_branch: false
  github_token: ""
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  test_mode: bool
  app_base_url: str?
  factory_reset: bool?
  marketing_page_enabled: bool?
  dev_use_main_branch: bool?
  github_token: password?
