name: "Vaultwarden (Bitwarden) (Custom)"
version: "0.3.2"
slug: vaultwarden
description: "Open source password management solution (Custom Build)"
url: "https://github.com/faserf/hassio-addons"
init: false
arch:
  - aarch64
  - amd64
options:
  log_level: info
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  request_size_limit: 10485760
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  ssl: bool
  certfile: str
  keyfile: str
  request_size_limit: int
ports:
  7277/tcp: 7277
ports_description:
  7277/tcp: Vaultwarden Web interface
ingress: true
ingress_entry: "/"
ingress_port: 7277
panel_icon: mdi:shield-key
map:
  - ssl
# image: ghcr.io/faserf/hassio-addons-vaultwarden-{arch}