name: BentoPDF
version: 0.1.0
slug: bentopdf
description: Self-hosted, privacy-first PDF toolkit
url: https://github.com/FaserF/hassio-addons/tree/master/bentopdf
arch:
  - aarch64
  - amd64

init: false
map:
  - ssl:rw
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: str?
  keyfile: str?
ports:
  8035/tcp: 8035
ports_description:
  8035/tcp: Web Interface (HTTP/HTTPS)
ingress: true
panel_icon: mdi:file-pdf-box
