name: BentoPDF
version: "1.1.1"
slug: bentopdf
image: ghcr.io/faserf/hassio-addons-bentopdf-{arch}
description: Self-hosted, privacy-first PDF toolkit
url: https://github.com/FaserF/hassio-addons/tree/master/bentopdf
arch:
  - aarch64
  - amd64

init: false
map:
  - ssl:rw
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  log_level: info
schema:
  ssl: bool
  certfile: str?
  keyfile: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
ports:
  8035/tcp: 8035
ports_description:
  8035/tcp: Web Interface (HTTP/HTTPS)
ingress: true
ingress_port: 8035
panel_icon: mdi:file-pdf-box
