name: Freenom-dns-updater
version: 1.7.1
slug: freenom-dns-updater
description:
  Freenom Registrar Domain Management - update dns records, Manage (add/update/remove)
  a domain's dns record, auto renew domains and more.
url: https://github.com/FaserF/hassio-addons/tree/master/freenom-dns-updater
arch:
  - aarch64
  - amd64
startup: application
boot: auto
map:
  - share:rw
ingress: false
init: false
panel_icon: mdi:web-box
options:
  config_file:
  update_time_in_seconds: 86400
schema:
  config_file: str
  update_time_in_seconds: int
