arch:
- aarch64
- amd64
description: Unsupported - Freenom Registrar Domain Management (Freenom service discontinued)
  (Unsupported)
init: false
map:
- share:rw
name: Freenom-dns-updater (Unsupported)
options:
  config_file: null
  update_time_in_seconds: 86400
panel_icon: mdi:web-box
schema:
  config_file: str
  update_time_in_seconds: int
slug: freenom-dns-updater
url: https://github.com/FaserF/hassio-addons/tree/master/freenom-dns-updater
version: 2.0.1-dev-2f099d7
