name: "ShieldFile"
version: "1.0.2"
slug: "shieldfile"
description: "Secure, Web-based File Manager (SFTP over HTTPS)"
url: "https://github.com/FaserF/hassio-addons/tree/master/ShieldFile"
startup: services
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
boot: auto
host_network: true
map:
  - config:rw
  - ssl:rw
  - share:rw
  - media:rw
  - backup:rw
options:
  certfile: "fullchain.pem"
  keyfile: "privkey.pem"
  users:
    - username: "admin"
      password: "changeme"
  base_directory: "/share"
  port: 8443
  log_level: "info"
schema:
  certfile: str
  keyfile: str
  users:
    - username: str
      password: str
  base_directory: str
  port: port
  log_level: list(debug|info|error|warning)
image: "ghcr.io/faserf/shieldfile-{arch}"
