name: "ShieldFile (Edge)"
version: "2.3.1-dev-c70fff0"
slug: "shieldfile"
description: "Secure, Web-based File Manager (SFTP over HTTPS)"
url: "https://github.com/FaserF/hassio-addons/tree/master/ShieldFile"
arch:
  - aarch64
  - amd64
init: false
ingress: true
panel_icon: mdi:shield-lock
ports:
  8443/tcp: 18443
ports_description:
  8443/tcp: "Direct Secure Access (HTTPS)"
map:
  - homeassistant_config:rw
  - ssl:rw
  - share:rw
  - media:rw
  - backup:rw
options:
  certfile: "fullchain.pem"
  keyfile: "privkey.pem"
  users:
    - username: "admin"
      password: "changeme1234"
  base_directory: "/share"
  port: 8443
  log_level: "info"
schema:
  certfile: str
  keyfile: str
  users:
    - username: str
      password: str
  base_directory: str
  port: port
  log_level: list(trace|debug|info|notice|warning|error|fatal)
