---
blank_issues_enabled: false
contact_links:
  - name: ðŸ†• New App Request
    url: https://faserf.github.io/hassio-addons/requests.html
    about: Want a new app? Read why I don't accept app requests (but feature requests are welcome!)
  - name: ðŸ“– Documentation
    url: https://faserf.github.io/hassio-addons
    about: Read the official documentation for these apps.
