---
blank_issues_enabled: false
contact_links:
  - name: ðŸ†• New App Request
    url: https://github.com/FaserF/hassio-apps/blob/main/.github/NEW_ADDON_REQUEST.md
    about: Want a new app? Read why I don't accept app requests (but feature requests are welcome!)
