name: Tiny Tiny RSS
version: 1.0.0
slug: tt-rss
description: A web-based news feed (RSS/Atom) reader and aggregator
url: https://tt-rss.org
arch:
  - aarch64
  - amd64
startup: services

map:
  - ssl:rw

options:
  self_url: ""
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  log_level: info

schema:
  self_url: str?
  ssl: bool
  certfile: str
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  reset_database: bool?
  reset_database_confirm: bool?

init: false
hassio_api: true

ports:
  8280/tcp: 8280
  8281/tcp: 8281
ingress: true
ingress_port: 8280
panel_icon: mdi:rss
image: ghcr.io/faserf/hassio-addons-tt-rss-{arch}
