name: Tiny Tiny RSS
version: 0.1.0
slug: tt-rss
description: A web-based news feed (RSS/Atom) reader and aggregator
url: https://tt-rss.org
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: false
map:
  - config:rw
options: {}
schema: {}
ports:
  80/tcp: 80
ingress: true
ingress_port: 80
panel_icon: mdi:rss
image: ghcr.io/hassio-addons/tt-rss/{arch}
