name: OpenSSL
version: 1.8.1
slug: openssl
description: Generate self-signed certificates
url: https://github.com/FaserF/hassio-addons/tree/master/openssl
arch:
  - aarch64
  - amd64
image: ghcr.io/faserf/openssl-{arch}
map:
  - ssl:rw
init: false
options:
  website_name:
schema:
  website_name: str
