---
name: OpenSSL
version: 2.1.0
slug: openssl
description: Generate self-signed certificates
url: https://github.com/FaserF/hassio-addons/tree/master/openssl
arch:
  - aarch64
  - amd64
image: ghcr.io/faserf/hassio-addons-openssl-{arch}
map:
  - ssl:rw
init: false
options:
  website_name:
schema:
  website_name: str
# Edge sync trigger: 2026-01-08
