---
name: OpenSSL
version: 2.1.4
slug: openssl
description: Generate self-signed certificates
url: https://github.com/FaserF/hassio-addons/tree/master/openssl
arch:
  - aarch64
  - amd64
image: ghcr.io/faserf/hassio-addons-openssl-{arch}
map:
  - ssl:rw
init: false
options:
  website_name:
  log_level: info
schema:
  website_name: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)
