name: Paperless-ngx
version: 0.1.0
slug: paperless-ngx
description: Community-supported Paperless-ngx App for Home Assistant
url: https://github.com/paperless-ngx/paperless-ngx
arch:
  - aarch64
  - amd64
services:
  - mysql:need
init: false
map:
  - share:rw
  - media:rw
  - ssl
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: Web Interface
ingress: true
ingress_port: 8000
options:
  url:
  filename_format: '{created_year}/{correspondent}/{title}'
  time_zone: Europe/Berlin
  ocr_language: deu
  admin_user: admin
  admin_password: ""
  secret_key: changeme
  log_level: info
  reset_database: false
  reset_database_confirm: false
schema:
  url: url?
  filename_format: str
  time_zone: str
  ocr_language: str
  admin_user: str?
  admin_password: password?
  secret_key: password
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  reset_database: bool?
  reset_database_confirm: bool?
image: ghcr.io/faserf/hassio-addons-paperless-ngx-{arch}
