arch:
- aarch64
- amd64
description: Tuya Convert - Flash Tuya devices with open Source software (Beta/Deprecated)
  (Unsupported)
host_network: true
init: false
map:
- share:rw
name: tuya-convert BETA
options:
  accept_eula: 'false'
  backup_path: /share/tuya-convert/
  firmware: tasmota.bin
privileged:
- NET_ADMIN
schema:
  accept_eula: str
  backup_path: str
  firmware: str
slug: tuya-convert
startup: services
url: https://github.com/FaserF/hassio-addons/tree/master/tuya-convert
version: 0.1.8
