arch:
  - aarch64
  - amd64
description: Unsupported - Tuya-Convert flash utility (Tuya patched vulnerability, no longer works)

host_network: true
init: false
map:
  - share:rw
name: tuya-convert BETA
options:
  accept_eula: "false"
  backup_path: /share/tuya-convert/
  firmware: tasmota.bin
privileged:
  - NET_ADMIN
schema:
  accept_eula: str
  backup_path: str
  firmware: str
slug: tuya-convert
image: ghcr.io/faserf/hassio-addons-tuya-convert-{arch}
url: https://github.com/FaserF/hassio-addons/tree/master/tuya-convert
version: 0.2.0
