name: bt-mqtt-gateway
version: 1.6.6
slug: bt-mqtt-gateway
description: Bluetooth MQTT Gateway Server
url: https://github.com/FaserF/hassio-addons/tree/master/bt-mqtt-gateway
host_network: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
services:
  - mqtt:want
map:
  - share
init: false
host_dbus: true
panel_icon: mdi:bluetooth-transfer
options:
  config_path: "/share/bt-mqtt-gateway.yaml"
  debug: false
schema:
  config_path: str
  debug: bool
