name: "Home Assistant Test Instance (Edge)"
version: "0.2.5-dev-c70fff0"
slug: "ha_test_instance"
description: "A standalone Home Assistant Core instance for testing purposes."
url: "https://github.com/home-assistant/home-assistant"
arch:
  - aarch64
  - amd64
ports:
  8123/tcp: 18124
map:
  - homeassistant_config:rw
ingress: true
ingress_port: 8123
init: false
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|warning|error|fatal)
