name: "Home Assistant Test Instance"
version: "0.2.4"
slug: "ha_test_instance"
image: ghcr.io/faserf/hassio-addons-homeassistant-test-instance-{arch}
description: "A standalone Home Assistant Core instance for testing purposes."
url: "https://github.com/home-assistant/home-assistant"
arch:
  - aarch64
  - amd64
ports:
  8123/tcp: 8124
map:
  - homeassistant_config:rw
ingress: true
ingress_port: 8123
init: false
