name: "WhatsApp"
version: "0.2.1"
slug: "whatsapp"
description: "Home Assistant WhatsApp Backend (Baileys/Node.js)"
url: "https://github.com/FaserF/ha-whatsapp"
arch:
  - aarch64
  - amd64
init: false
map:
  - homeassistant_config:rw
panel_icon: mdi:whatsapp
options:
  log_level: info
schema:
  log_level: str
ports:
  8066/tcp: 8066
ingress: true
ingress_entry: /
