name: "WhatsApp"
version: "0.5.3"
slug: "whatsapp"
image: ghcr.io/faserf/hassio-addons-whatsapp-{arch}
description: "Home Assistant WhatsApp Backend (Baileys/Node.js)"
url: "https://github.com/FaserF/ha-whatsapp"
arch:
  - aarch64
  - amd64
init: false
map:
  - homeassistant_config:rw
panel_icon: mdi:whatsapp
options:
  log_level: info
  reset_session: false
  send_message_timeout: 25000
  keep_alive_interval: 30000
  mask_sensitive_data: false
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  reset_session: bool
  send_message_timeout: int
  keep_alive_interval: int
  mask_sensitive_data: bool
ports:
  8066/tcp: 8066
hassio_api: true
ingress: true
ingress_port: 8066
ingress_entry: /
