name: "WhatsApp"
version: "0.4.0"
slug: "whatsapp"
image: ghcr.io/faserf/hassio-addons-whatsapp-{arch}
description: "Home Assistant WhatsApp Backend (Baileys/Node.js)"
url: "https://github.com/FaserF/ha-whatsapp"
arch:
  - aarch64
  - amd64
init: false
map:
  - homeassistant_config:rw
panel_icon: mdi:whatsapp
options:
  log_level: info
schema:
  log_level: str
host_network: true
hassio_api: true
ingress: true
ingress_entry: /
# Edge sync trigger: 2026-01-08
