name: "WhatsApp"
version: "0.2.3"
slug: "whatsapp"
description: "Home Assistant WhatsApp Backend (Baileys/Node.js)"
url: "https://github.com/FaserF/ha-whatsapp"
arch:
  - aarch64
  - amd64
init: false
map:
  - homeassistant_config:rw
panel_icon: mdi:whatsapp
options:
  log_level: info
schema:
  log_level: str
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: WhatsApp API (for Integration)
ingress: true

ingress_entry: /
