name: "WhatsApp"
version: "0.0.1"
slug: "whatsapp"
description: "Home Assistant WhatsApp Backend (Playwright)"
url: "https://github.com/FaserF/ha-whatsapp"
startup: application
arch:
  - aarch64
  - amd64
init: false
map:
  - config:rw
options:
  log_level: info
schema:
  log_level: str
ports:
  8000/tcp: 8000
ingress: true
ingress_port: 8000
ingress_entry: /
