name: "WhatsApp"
version: "1.2.1"
slug: "whatsapp"
image: ghcr.io/faserf/hassio-addons-whatsapp-{arch}
description: "Home Assistant WhatsApp Backend (Baileys/Node.js). Uses Host Network (Port 8066 cannot be changed)."
url: "https://github.com/FaserF/ha-whatsapp"
arch:
  - aarch64
  - amd64
init: false
host_network: true
map:
  - homeassistant_config:rw
panel_icon: mdi:whatsapp
options:
  log_level: info
  reset_session: false
  send_message_timeout: 25000
  keep_alive_interval: 30000
  mask_sensitive_data: false
  webhook_enabled: false
  webhook_url: ""
  webhook_token: ""
  ui_auth_enabled: false
  ui_auth_password: ""
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  reset_session: bool
  send_message_timeout: int
  keep_alive_interval: int
  mask_sensitive_data: bool
  webhook_enabled: bool
  webhook_url: str?
  webhook_token: str?
  ui_auth_enabled: bool
  ui_auth_password: str?
ports:
  8066/tcp: 8066
hassio_api: true
ingress: true
ingress_port: 8066
ingress_entry: /
