---
name: N8n
version: 2.2.4
slug: n8n
description: "Workflow automation tool. N8n extends your Home Assistant with powerful workflow automation."
url: "https://github.com/faserf/hassio-addons/tree/master/addons/n8n"
arch:
  - aarch64
  - amd64
  - armv7
image: "ghcr.io/faserf/hassio-addons-n8n-{arch}"
ingress: true
ingress_port: 5678
init: false
panel_icon: mdi:workflow
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: str
  keyfile: str
ports:
  5678/tcp: 5678
ports_description:
  5678/tcp: Web Interface
