---
name: Switch LAN Play Server
version: 1.8.2-dev+8bfa663
slug: switch-lan-play-server
description: Nintendo Switch Lan Play -Server
url: https://github.com/FaserF/hassio-addons/tree/master/switch_lan_play_server
arch:
  - amd64
# image: local build only
panel_icon: mdi:local-area-network
init: false
schema:
  username: str?
  password: str?
ports:
  "11451": 11451
ports_description:
  11451/tcp: SLP Server Port
