---
name: Switch LAN Play Server
version: 2.1.4
slug: switch-lan-play-server
description: Nintendo Switch Lan Play -Server
url: https://github.com/FaserF/hassio-addons/tree/master/switch_lan_play_server
arch:
  - amd64
image: ghcr.io/faserf/hassio-addons-switch-lan-play-server-{arch}
panel_icon: mdi:local-area-network
init: false
options:
  log_level: info
schema:
  username: str?
  password: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
ports:
  "11451": 11451
ports_description:
  11451/tcp: SLP Server Port
