---
name: Wiki.JS V3 (Beta)
version: 0.4.0
slug: wiki.js3
image: ghcr.io/faserf/hassio-addons-wiki-{arch}

description: The most powerful and extensible open source Wiki software (Version 3 - Beta)
url: https://github.com/FaserF/hassio-addons/tree/master/wiki.js3
arch:
  # - aarch64 (nodejs does support aarch64, but nodejs musl not?)
  - amd64
map:
  - ssl
ingress: true
ingress_port: 3011
init: false
panel_icon: mdi:wikipedia
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  log_level: info
  reset_database: false
  reset_database_confirm: false
  db_password: "wikijs"
schema:
  ssl: bool
  certfile: str
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  reset_database: bool?
  reset_database_confirm: bool?
  db_password: password?
ports:
  3011/tcp: 3001
  3443/tcp: 3444
ports_description:
  3011/tcp: HTTP Entrance port (internal port 3011, external port 3001)
  3443/tcp: HTTPS/SSL Entrance port
