---
name: Wiki.JS V3 (Beta)
version: 0.3.1
slug: wiki.js3
image: ghcr.io/faserf/hassio-addons-wiki-{arch}

description: The most powerful and extensible open source Wiki software (Version 3 - Beta)
url: https://github.com/FaserF/hassio-addons/tree/master/wiki.js3
arch:
  # - aarch64 (nodejs does support aarch64, but nodejs musl not?)
  - amd64
map:
  - ssl
ingress: true
init: false
panel_icon: mdi:wikipedia
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  log_level: info
  db_password: "wikijs"
schema:
  ssl: bool
  certfile: str
  keyfile: str
  log_level: list(error|warn|info|debug)?
  reset_database: bool?
  reset_database_confirm: bool?
  db_password: password?
ports:
  3000/tcp: 3001
  3443/tcp: 3444
ports_description:
  3000/tcp: HTTP Entrance port
  3443/tcp: HTTPS/SSL Entrance port
