name: Update Docs

on:
  push:
    branches:
      - main
    paths:
      - "**/config.yaml"
      - ".scripts/generate_docs.py"
      - "docs/css/**"
  workflow_dispatch:

jobs:
  update-docs:
    name: ğŸ“ Update Documentation
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: ğŸ“¦ Install Dependencies
        run: |
          pip install pyyaml

      - name: ğŸ“„ Generate Docs
        run: |
          python3 .scripts/generate_docs.py

      - name: ğŸš€ Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto-update index.html"
          file_pattern: "docs/index.html"
